### ISSUE TITLE
Training on train/val split issue.

### ISSUE THREAD

**Issue by Sheldonmao** [eldar/snes#1]
Hi I noticed in the default `config/config.yaml` the trainval_split is set to false, and there is no such `train_val_split.pkl` file in extra data:

```
 ## here is what I found  in file config/config.yaml
  trainval_split: false
  split_file: "train_val_split.pkl"
`````

Does it suggest that the following example training script uses full training images instead of a train/val split of views (as described in the paper)?  

`(EXP=car/structured ID=157_17286_33548; python exp_runner.py gpu=0 mode=train config.file=exp/$EXP/config.yaml config.exp_name=$EXP/${ID} dataset.instance=\'$ID\')`

If it does, how should I reproduce the results in the paper? To be more specific, after setting `trainval_split: true`, I found two potential split files (namely `train_val_split_official.pkl` and `train_val_structured_split.pkl`), which should I use?

**Comment by eldar** [comment]
Hi, I apologise for the late reply. Both splits are used to reproduce the results in the paper. The official and the structured splits are both used in the paper and are described in sections 5.2 and 5.3 respectively. Structured split is created specifically for our paper and excludes a portion of the object on its one side in order to test the ability of the model to perform symmetric reconstruction. I hope that helps!
